---
kind: pipeline
type: docker
name: pre-commit

trigger:
  event:
    exclude:
    - tag

steps:
- name: check hooks
  image: ${MZ_DOCKER_REGISTRY}/pre-commit:latest
  commands:
    - pre-commit run --all-files --verbose --show-diff-on-failure


---
kind: pipeline
type: docker
name: ubuntu-1804-clang

trigger:
  event:
    exclude:
    - tag

workspace:
  path: /drone/src
environment:
  CONAN_CPU_COUNT: 12
  CONAN_USER_HOME: /drone/src

steps:
- name: submodules
  image: alpine/git
  commands:
    - git fetch --tags
    - git submodule update --init --recursive

- name: build
  image: ${MZ_DOCKER_REGISTRY}/builder-1804-clang:latest
  commands:
    - cd build
    - bash ./generator.sh mode=release compiler=clang generator=ninja location=inside -DBUILD_XDISPATCH2_TESTS=ON
    - cd clang-ninja-release
    - ninja -j 12

- name: package
  image: ${MZ_DOCKER_REGISTRY}/builder-1804-clang:latest
  commands:
    - python3 build/conan_package.py --create
  when:
    ref:
      - refs/pull/*/head

- name: test
  image: ${MZ_DOCKER_REGISTRY}/builder-1804-clang:latest
  environment:
    USER: test_runner
    # XDISPATCH2_TRACE: 1
  commands:
    - cd build/clang-ninja-release/bin
    - ./xdispatch2_tests
    - ./xdispatch2_platform_demo


---
kind: pipeline
type: docker
name: conan

trigger:
  event:
    include:
    - tag

workspace:
  path: /drone/src
environment:
  CONAN_CPU_COUNT: 12
  CONAN_USER_HOME: /drone/src

steps:
- name: submodules
  image: alpine/git
  commands:
    - git fetch --tags
    - git submodule update --init --recursive

- name: configure
  image: ${MZ_DOCKER_REGISTRY}/builder-1804-clang:latest
  commands:
    - cd build
    - bash ./generator.sh mode=release compiler=clang generator=ninja location=inside -DBUILD_XDISPATCH2_TESTS=ON

- name: package & upload
  image: ${MZ_DOCKER_REGISTRY}/builder-1804-clang:latest
  commands:
    - python3 build/conan_package.py --create --upload


---
kind: pipeline
type: exec
name: darwin-macos

trigger:
  event:
    exclude:
    - tag

platform:
  os: darwin
  arch: amd64

steps:
- name: submodules
  commands:
    - git fetch --tags
    - git submodule update --init --recursive

- name: build
  commands:
    - ln -s /Users/$${USER}/Library $${HOME}/Library
    - cd build
    - bash ./generator.sh mode=release compiler=clang generator=ninja location=inside -DBUILD_XDISPATCH2_TESTS=ON
    - cd clang-ninja-release
    - ninja -j 12

- name: package
  commands:
    - python3 build/conan_package.py --create
  when:
    ref:
      - refs/pull/*/head

- name: test
  commands:
    - cd build/clang-ninja-release/bin
    - ./xdispatch2_tests
    - ./xdispatch2_platform_demo
  when:
    ref:
      - refs/heads/master
      - refs/pull/*/head


---
kind: pipeline
type: exec
name: darwin-macos (tag)

trigger:
  event:
    include:
    - tag
depends_on:
- conan

platform:
  os: darwin
  arch: amd64

steps:
- name: submodules
  commands:
    - git fetch --tags
    - git submodule update --init --recursive

- name: configure
  commands:
    - ln -s /Users/$${USER}/Library $${HOME}/Library
    - cd build
    - bash ./generator.sh mode=release compiler=clang generator=ninja location=inside -DBUILD_XDISPATCH2_TESTS=ON

- name: package & upload
  commands:
    - python3 build/conan_package.py --build --upload


---
kind: pipeline
type: exec
name: darwin-ios

trigger:
  event:
    exclude:
    - tag

platform:
  os: darwin
  arch: amd64

steps:
- name: submodules
  commands:
    - git fetch --tags
    - git submodule update --init --recursive

- name: build
  commands:
    - ln -s /Users/$${USER}/Library $${HOME}/Library
    - cd build
    - bash ./generator.sh mode=release compiler=ios generator=makefiles location=inside -DBUILD_XDISPATCH2_TESTS=ON
    - cd ios-makefiles-release
    - make -j 12

- name: package
  commands:
    - python3 build/conan_package.py --create
  when:
    ref:
      - refs/pull/*/head


---
kind: pipeline
type: exec
name: darwin-ios (tag)

trigger:
  event:
    include:
    - tag
depends_on:
- conan

platform:
  os: darwin
  arch: amd64

steps:
- name: submodules
  commands:
    - git fetch --tags
    - git submodule update --init --recursive

- name: configure
  commands:
    - ln -s /Users/$${USER}/Library $${HOME}/Library
    - cd build
    - bash ./generator.sh mode=release compiler=ios generator=makefiles location=inside -DBUILD_XDISPATCH2_TESTS=ON

- name: package & upload
  commands:
    - python3 build/conan_package.py --build --upload


---
kind: pipeline
type: exec
name: windows-msvc64

trigger:
  event:
    exclude:
    - tag

platform:
  os: windows
  arch: amd64

steps:
- name: submodules
  commands:
    - git fetch --tags
    - git submodule update --init --recursive

- name: build
  commands:
    - cd build
    - .\generator.bat release ninja_64 inside -DBUILD_XDISPATCH2_TESTS=ON
    - cd win32-ninja_64-release
    - ninja

- name: package
  commands:
    - python3 build/conan_package.py --create
  when:
    ref:
      - refs/pull/*/head

- name: test
  commands:
    - cd build/win32-ninja_64-release/bin
    - .\xdispatch2_tests.exe
    - .\xdispatch2_platform_demo.exe
  when:
    ref:
      - refs/heads/master
      - refs/pull/*/head


---
kind: pipeline
type: exec
name: windows-msvc64 (tag)

trigger:
  event:
    include:
    - tag
depends_on:
- conan

platform:
  os: windows
  arch: amd64

steps:
- name: submodules
  commands:
    - git fetch --tags
    - git submodule update --init --recursive

- name: configure
  commands:
    - cd build
    - .\generator.bat release ninja_64 inside -DBUILD_XDISPATCH2_TESTS=ON

- name: package & upload
  commands:
    - python3 build/conan_package.py --build --upload
